### ISSUE TITLE
Serial Read Bottleneck

### ISSUE THREAD

**Issue by MindaugasMeskauskas** [pihome-shc/pihome#118]
### Summary:
Yesterday for first time I encountered strange issue, all 3 of my nodes were reporting wrong temperature. Boiler was ON for longer as it should have been. At first I couldn’t tell what was the problem, as all 3 nodes frequently were updating DB with “current” temperature. Next morning I checked graphs (see below) and you can see that right temperature curve appeared about 6 hours late. As it affected all notes the bottleneck must have been on receiving end.

![20200204_080152000_iOS](https://user-images.githubusercontent.com/5328862/73754705-b35cfb00-475c-11ea-8367-944b430b4b5e.png)
Spikes shown on graph around 1am, was me testing nodes at around 10pm.

![20200204_080651000_iOS](https://user-images.githubusercontent.com/5328862/73754808-e1423f80-475c-11ea-8b5b-013e0e5b0438.png)
Raspberry Pi temp curve looks as it should (different script, not affected by serial read)

### Observations:
Haven’t done any testing, but this is what I have observed. All of this is my closest guess. Ref similar issue on [stackoverflow](https://stackoverflow.com/questions/19908167/reading-serial-data-in-realtime-in-python)

serialgw.py script has time.sleep(1) in its loop, so it means if serial port receives more than 1 message a second, messages will start to pile up in queue and will be read out one by one every second.
To delay serial read by this much (6h) about 21600 additional messages needed to be written/read in short period of time (not sure how many messages are generated in normal circumstances).

### Possible Solution:
Part 1: In general we are not expecting more than 1 message per second in average, but to prevent such unexpected behaviour and provide future proof, serialgw.py loop should be implemented without sleep as well as without causing extensive additional resources on CPU.

Part 2: Number of additional messages looks to be way too high. Need to be investigate what could have generated all of them in such sort time.

**Comment by pihome-shc** [comment]
@MindaugasMeskauskas, 
i know this issue, when last time i installed a 32 zone UFH system in Ireland
34 temperature sensors, 
10 Zone Controller 
1 Boiler Controller 
if i do maths correctly: 
Temperature sensors sends 3 messages: temperature, battery volt, battery %
Zone Controller: 4 messages per controller with ack to keep controller alive in system. 


Node | # | rx | tx | total
-- | -- | -- | -- | --
Sensor | 32 | 0 | 3 | 96
Zone | 10 | 4 | 4 | 160
Boiler | 1 | 1 | 1 | 1
Total |   |   |   | 257



Total 257 messages to process per minute for script it was over the limit and script was causing some serious issues as script couldn't go thought all the messages in 60 seconds while boiler.php updated message_out table ready for next round. 

### Workaround: 
i decreased message_out per zone controller from 4 to 1 (manually set ack to 0 and leave one ack 1). 
and inside wifigw.py  `time.sleep(0.1)`

back to what could have generated that many messages:
when heating is on temperature sensors send reading every 60ish seconds because temperature is changing. You have three zone so i m assuming, one zone controller, one boiler controller and three temperature sensors. your system have to deal with 27 messages every 60 seconds and if script go for sleep for 1 seconds we lose 30 seconds in sleep time per 60 seconds so its very close to cause queue. 

Node | # | rx | tx | total
-- | -- | -- | -- | --
Sensor | 3 | 0 | 3 | 9
Zone | 1 | 4 | 4 | 16
Boiler | 1 | 1 | 1 | 2
Total |   |   |   | 27

i m not sure how cpu will react with no sleep time. 
here is short video when boiler.php run and update message_out table, you can see cpu usage goes nearly 100% on both core. 
https://www.dropbox.com/s/xwmobktyrtehbbc/2020-02-04%2023.02.54.mov?dl=0

**Comment by MindaugasMeskauskas** [comment]
@pihome-shc 
Did some digging yesterday and found that in average 30-40 messages were processed per minute. Max observed was 47. That is a bit high, but not to overload system, as it happened. Checked all processed messages and it looks like I haven't disabled debugging on GW and it prints all debugging info to serial. Will test that next. Still puzzled what could have caused such delay. Could have gateway debug printed so many messages in some scenario?

FYI, my setup:
2 temperature node - only for testing in different rooms or as redundancy
1 water tank node - 2 sensors but returns average
0 Zone - No zone controller (but guessing messages are still sent out as zones are setup in interface)
1 Boiler - but would be nice to have second source :) e.g. water tank is gas and electric.

**Comment by pihome-shc** [comment]
@MindaugasMeskauskas 
yes debug messages are processed as well even thought they dont get into database but python script still have to process them and ignore them. did you change sleep time to lower value? or remove it all together.

**Comment by MindaugasMeskauskas** [comment]
@pihome-shc 
Had no time to check it further. Haven't touched anything. Still running original code and with GW debug enabled. Seems to be running OK at the moment.

**Comment by MindaugasMeskauskas** [comment]
Finally looked at this again. Observed that GW sometimes get into situation where it produces 200+ debug messages without any payload. Example below:

`0;255;3;0;9;1388779 TSF:MSG:READ,67-67-67,s=67,c=3,t=67,pt=2,l=8,sg=0:67
0;255;3;0;9;1388800 !TSF:MSG:LEN=8,EXP=15`

Have no node 67 so not sure if this some interference or what, but know that I don't need that information of incomplete incoming messages flooding serial buffer. If simply disabling debugging, GW stops writing to serial, but strangely still reads serial port :/ All Serial GW examples I found have debugging enabled which is OK for setting up, but not for production and no explanation how do it without enabling debugging. Played with parameters from MySensors library MyConfig.h and found that if disabling debug by removing line `#define MY_DEBUG` and adding `#define MY_SERIALDEVICE Serial` only messages are written to serial. Current message rate per minute for my setup is 5-17 and that is way better than before with 30-40 or even above 200 in rare circumstances.

Haven't done any code changes is serialgw.py, which is not required with current message rate.

**Comment by pihome-shc** [comment]
@MindaugasMeskauskas may be someone in your nearby have mysensors nodes :)

**Comment by pihome-shc** [comment]
@MindaugasMeskauskas are you using irq pin on your nRF (i m assuming you are using nRF radio) i know with irp pin it improves buffering and message processing.

**Comment by pihome-shc** [comment]
is this issue need any further work?
